web:
  image: iridior/practicablog
  ports:
    - "8080:8080"
  links:
    - db
    - analizador
  environment:
    SPRING_DATASOURCE_URL: jdbc:mysql://db/test
    PROPERTY_SERVICIO_ANALIZADOR: analizador:8081
    
analizador:
  image: iridior/practicaanalizador
  ports:
    - "8081:8081"

db:
  environment:
    MYSQL_ROOT_PASSWORD: pass
    MYSQL_DATABASE: test
    MYSQL_USER: admin
    MYSQL_PASSWORD: admin
  image: mysql:5.7